SET SESSION FOREIGN_KEY_CHECKS = 0;

INSERT
IGNORE INTO  `js_sys_module`(`module_code`, `module_name`, `description`, `main_class_name`, `current_version`, `upgrade_info`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`) VALUES (''pm'', ''项目管理'', ''项目管理'', ''net.syzc.modules.pm.PmProjBaseController'', ''4.2.4'', ''upgrade 2021-04-13 18:08:40 (4.2.3 -> 4.2.4)'', ''0'', ''system'', ''2021-04-13 13:58:11'', ''system'', ''2021-04-13 18:08:40'', NULL);

commit;

INSERT
IGNORE INTO  `js_sys_menu`(`menu_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `menu_name`, `menu_type`, `menu_href`, `menu_target`, `menu_icon`, `menu_color`, `menu_title`, `permission`, `weight`, `is_show`, `sys_code`, `module_codes`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`) VALUES (''1381568082755850240'', ''0'', ''0,'', 9000, ''0000009000,'', ''0'', 0, ''项目管理'', ''项目管理'', ''1'', '''', '''', ''fa fa-institution'', '''', '''', '''', 40, ''1'', ''default'', ''pm'', ''0'', ''system'', ''2021-04-12 19:21:14'', ''system'', ''2021-04-14 09:39:53'', '''', '''', '''', '''', '''', '''', '''', '''', '''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT
IGNORE INTO  `js_sys_menu`(`menu_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `menu_name`, `menu_type`, `menu_href`, `menu_target`, `menu_icon`, `menu_color`, `menu_title`, `permission`, `weight`, `is_show`, `sys_code`, `module_codes`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`) VALUES (''1381913862833754112'', ''1381568082755850240'', ''0,1381568082755850240,'', 30, ''0000009000,0000000030,'', ''0'', 1, ''项目管理/项目信息'', ''项目信息'', ''1'', ''/pm/pmProjBase/list'', '''', ''fa fa-book'', '''', ''项目信息'', '''', 40, ''1'', ''default'', ''pm'', ''0'', ''system'', ''2021-04-13 18:15:14'', ''system'', ''2021-04-13 19:17:35'', '''', '''', '''', '''', '''', '''', '''', '''', '''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT
IGNORE INTO  `js_sys_menu`(`menu_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `menu_name`, `menu_type`, `menu_href`, `menu_target`, `menu_icon`, `menu_color`, `menu_title`, `permission`, `weight`, `is_show`, `sys_code`, `module_codes`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`) VALUES (''1381929255062007808'', ''1381913862833754112'', ''0,1381568082755850240,1381913862833754112,'', 30, ''0000009000,0000000030,0000000030,'', ''1'', 2, ''项目管理/项目信息/查看'', ''查看'', ''2'', '''', '''', '''', '''', '''', ''pm:pmProjBase:view'', 40, ''1'', ''default'', ''pm'', ''0'', ''system'', ''2021-04-13 19:16:24'', ''system'', ''2021-04-13 19:16:44'', '''', '''', '''', '''', '''', '''', '''', '''', '''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT
IGNORE INTO   `js_sys_menu`(`menu_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `menu_name`, `menu_type`, `menu_href`, `menu_target`, `menu_icon`, `menu_color`, `menu_title`, `permission`, `weight`, `is_show`, `sys_code`, `module_codes`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`) VALUES (''1382229451805200384'', ''1381913862833754112'', ''0,1381568082755850240,1381913862833754112,'', 60, ''0000009000,0000000030,0000000060,'', ''1'', 2, ''项目管理/项目信息/编辑'', ''编辑'', ''2'', '''', '''', '''', '''', '''', ''pm:pmProjBase:edit'', 40, ''1'', ''default'', ''pm'', ''0'', ''system'', ''2021-04-14 15:09:17'', ''system'', ''2021-04-14 15:09:17'', '''', '''', '''', '''', '''', '''', '''', '''', '''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

commit;
INSERT
IGNORE INTO   `js_sys_role_menu`(`role_code`, `menu_code`) VALUES (''corpAdmin'', ''1381568082755850240'');
INSERT
IGNORE INTO   `js_sys_role_menu`(`role_code`, `menu_code`) VALUES (''corpAdmin'', ''1381913862833754112'');
INSERT
IGNORE INTO   `js_sys_role_menu`(`role_code`, `menu_code`) VALUES (''corpAdmin'', ''1381929255062007808'');
INSERT
IGNORE INTO   `js_sys_role_menu`(`role_code`, `menu_code`) VALUES (''corpAdmin'', ''1382229451805200384'');


-- replace into
commit;

INSERT
IGNORE INTO  `js_gen_table`(`table_name`, `class_name`, `comments`, `parent_table_name`, `parent_table_fk_name`, `data_source_name`, `tpl_category`, `package_name`, `module_name`, `sub_module_name`, `function_name`, `function_name_simple`, `function_author`, `gen_base_dir`, `options`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`) VALUES (''pm_proj_base'', ''PmProjBase'', ''项目项目信息'', '''', '''', '''', ''crud'', ''net.syzc.modules'', ''pm'', '''', ''项目项目信息'', ''项目项目信息'', ''张文相'', ''D:\\Code\\github\\qinqoushui\\QProject\\pm'', ''{\"treeViewName\":\"\",\"isHaveDelete\":\"1\",\"bpmFormKey\":\"\",\"treeViewCode\":\"\",\"isFileUpload\":\"0\",\"isHaveDisableEnable\":\"1\",\"isBpmForm\":\"0\",\"isImageUpload\":\"0\"}'', ''system'', ''2021-04-12 19:17:17'', ''system'', ''2021-04-13 19:04:41'', '''');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087569145856'', ''pm_proj_base'', ''id'', 10, ''varchar(20)'', ''编号'', ''编号'', ''id'', ''String'', ''1'', ''0'', ''1'', '''', '''', '''', ''EQ'', ''1'', ''hidden'', ''{\"isNewLine\":\"\",\"fieldValid\":\"abc\",\"dictName\":\"\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087590117376'', ''pm_proj_base'', ''project_name'', 20, ''varchar(200)'', ''项目名称'', ''项目名称'', ''projectName'', ''String'', '''', ''0'', ''1'', ''1'', ''1'', ''1'', ''LIKE'', ''1'', ''input'', ''{\"isNewLine\":\"\",\"fieldValid\":\"\",\"dictName\":\"\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087602700288'', ''pm_proj_base'', ''status'', 30, ''char(1)'', ''状态'', ''状态（0正常 1删除 2停用）'', ''status'', ''String'', '''', ''0'', ''1'', '''', ''1'', ''1'', ''EQ'', '''', ''select'', ''{\"isNewLine\":\"\",\"fieldValid\":\"\",\"dictName\":\"sys_search_status\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"sys_search_status\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087615283200'', ''pm_proj_base'', ''create_by'', 40, ''varchar(64)'', ''创建者'', ''创建者'', ''createBy'', ''String'', '''', ''0'', ''1'', '''', '''', '''', ''EQ'', '''', ''input'', ''{\"isNewLine\":\"\",\"fieldValid\":\"\",\"dictName\":\"\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087644643328'', ''pm_proj_base'', ''create_date'', 50, ''datetime'', ''创建时间'', ''创建时间'', ''createDate'', ''java.util.Date'', '''', ''0'', ''1'', '''', '''', '''', ''EQ'', '''', ''input'', ''{\"isNewLine\":\"\",\"fieldValid\":\"\",\"dictName\":\"\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087661420544'', ''pm_proj_base'', ''update_by'', 60, ''varchar(64)'', ''更新者'', ''更新者'', ''updateBy'', ''String'', '''', ''0'', ''1'', ''1'', '''', '''', ''EQ'', '''', ''input'', ''{\"isNewLine\":\"\",\"fieldValid\":\"\",\"dictName\":\"\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087674003456'', ''pm_proj_base'', ''update_date'', 70, ''datetime'', ''更新时间'', ''更新时间'', ''updateDate'', ''java.util.Date'', '''', ''0'', ''1'', ''1'', ''1'', '''', ''EQ'', '''', ''input'', ''{\"isNewLine\":\"\",\"fieldValid\":\"\",\"dictName\":\"\",\"gridRowCol\":\"6/4/8\",\"dictType\":\"\"}'');
INSERT IGNORE INTO  `js_gen_table_column`(`id`, `table_name`, `column_name`, `column_sort`, `column_type`, `column_label`, `comments`, `attr_name`, `attr_type`, `is_pk`, `is_null`, `is_insert`, `is_update`, `is_list`, `is_query`, `query_type`, `is_edit`, `show_type`, `options`) VALUES (''1381567087690780672'', ''pm_proj_base'', ''remarks'', 80, ''varchar(500)'', ''备注信息'', ''备注信息'', ''remarks'', ''String'', '''', ''1'', ''1'', ''1'', ''1'', ''1'', ''LIKE'', ''1'', ''textarea'', ''{\"isNewLine\":\"1\",\"fieldValid\":\"\",\"dictName\":\"\",\"gridRowCol\":\"12/2/10\",\"dictType\":\"\"}'');

commit;

